# Generated by Django 4.2.30 on 2026-05-25 04:43

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(db_column='product_id', default=uuid.uuid4, primary_key=True, serialize=False)),
                ('sku', models.CharField(max_length=100, unique=True)),
                ('product_name', models.CharField(max_length=200)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_fragile', models.BooleanField(default=False)),
                ('is_hazardous', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'products',
            },
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.UUIDField(db_column='category_id', default=uuid.uuid4, primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'product_categories',
            },
        ),
        migrations.CreateModel(
            name='ProductStorageRule',
            fields=[
                ('id', models.UUIDField(db_column='rule_id', default=uuid.uuid4, primary_key=True, serialize=False)),
                ('allowed_zone_type', models.CharField(max_length=50)),
                ('max_stack_height', models.IntegerField()),
                ('required_temperature', models.DecimalField(decimal_places=2, max_digits=5)),
                ('orientation_rule', models.CharField(max_length=100)),
                ('product', models.ForeignKey(db_column='product_id', on_delete=django.db.models.deletion.CASCADE, related_name='storage_rules', to='products.product')),
            ],
            options={
                'db_table': 'product_storage_rules',
            },
        ),
        migrations.CreateModel(
            name='ProductDimension',
            fields=[
                ('id', models.UUIDField(db_column='dimension_id', default=uuid.uuid4, primary_key=True, serialize=False)),
                ('length', models.DecimalField(decimal_places=2, max_digits=10)),
                ('width', models.DecimalField(decimal_places=2, max_digits=10)),
                ('height', models.DecimalField(decimal_places=2, max_digits=10)),
                ('box_length', models.DecimalField(decimal_places=2, max_digits=10)),
                ('box_width', models.DecimalField(decimal_places=2, max_digits=10)),
                ('box_height', models.DecimalField(decimal_places=2, max_digits=10)),
                ('product', models.ForeignKey(db_column='product_id', on_delete=django.db.models.deletion.CASCADE, related_name='dimensions', to='products.product')),
            ],
            options={
                'db_table': 'product_dimensions',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(db_column='category_id', on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.productcategory'),
        ),
    ]
