# Generated by Django 4.2.30 on 2026-06-08 06:04

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bin',
            fields=[
                ('id', models.UUIDField(db_column='bin_id', default=uuid.uuid4, primary_key=True, serialize=False)),
                ('bin_code', models.CharField(max_length=50, unique=True)),
                ('max_capacity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('current_capacity', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_occupied', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'bins',
            },
        ),
        migrations.CreateModel(
            name='CADObject',
            fields=[
                ('id', models.UUIDField(db_column='object_id', default=uuid.uuid4, primary_key=True, serialize=False)),
                ('object_type', models.CharField(max_length=50)),
                ('detected_label', models.CharField(max_length=100)),
                ('confidence_score', models.DecimalField(decimal_places=4, max_digits=5)),
                ('x', models.DecimalField(decimal_places=4, max_digits=10)),
                ('y', models.DecimalField(decimal_places=4, max_digits=10)),
                ('z', models.DecimalField(decimal_places=4, max_digits=10)),
                ('width', models.DecimalField(decimal_places=4, max_digits=10)),
                ('height', models.DecimalField(decimal_places=4, max_digits=10)),
                ('depth', models.DecimalField(decimal_places=4, max_digits=10)),
            ],
            options={
                'db_table': 'cad_objects',
            },
        ),
        migrations.CreateModel(
            name='NavigationNode',
            fields=[
                ('id', models.UUIDField(db_column='node_id', default=uuid.uuid4, primary_key=True, serialize=False)),
                ('node_name', models.CharField(max_length=100)),
                ('node_type', models.CharField(max_length=50)),
                ('x', models.DecimalField(decimal_places=4, max_digits=10)),
                ('y', models.DecimalField(decimal_places=4, max_digits=10)),
                ('z', models.DecimalField(decimal_places=4, max_digits=10)),
                ('connections', models.JSONField(blank=True, default=list)),
            ],
            options={
                'db_table': 'navigation_graph',
            },
        ),
        migrations.CreateModel(
            name='OptimizedRoute',
            fields=[
                ('id', models.UUIDField(db_column='route_id', default=uuid.uuid4, primary_key=True, serialize=False)),
                ('start_location', models.CharField(max_length=100)),
                ('distance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estimated_time', models.IntegerField(help_text='Estimated time in seconds')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'optimized_routes',
            },
        ),
        migrations.CreateModel(
            name='Rack',
            fields=[
                ('id', models.UUIDField(db_column='rack_id', default=uuid.uuid4, primary_key=True, serialize=False)),
                ('rack_code', models.CharField(max_length=50, unique=True)),
                ('max_weight', models.DecimalField(decimal_places=2, max_digits=10)),
                ('x', models.DecimalField(decimal_places=4, max_digits=10)),
                ('y', models.DecimalField(decimal_places=4, max_digits=10)),
                ('z', models.DecimalField(decimal_places=4, max_digits=10)),
                ('width', models.DecimalField(decimal_places=4, max_digits=10)),
                ('height', models.DecimalField(decimal_places=4, max_digits=10)),
                ('depth', models.DecimalField(decimal_places=4, max_digits=10)),
                ('rotation_angle', models.DecimalField(decimal_places=4, max_digits=8)),
            ],
            options={
                'db_table': 'racks',
            },
        ),
        migrations.CreateModel(
            name='Shelf',
            fields=[
                ('id', models.UUIDField(db_column='shelf_id', default=uuid.uuid4, primary_key=True, serialize=False)),
                ('shelf_number', models.IntegerField()),
                ('max_weight', models.DecimalField(decimal_places=2, max_digits=10)),
                ('height_from_ground', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rack', models.ForeignKey(db_column='rack_id', on_delete=django.db.models.deletion.CASCADE, related_name='shelves', to='warehouse.rack')),
            ],
            options={
                'db_table': 'shelves',
            },
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.UUIDField(db_column='warehouse_id', default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('location', models.TextField(blank=True, null=True)),
                ('total_area_sqft', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'warehouses',
            },
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.UUIDField(db_column='zone_id', default=uuid.uuid4, primary_key=True, serialize=False)),
                ('zone_name', models.CharField(max_length=100)),
                ('zone_type', models.CharField(max_length=50)),
                ('x', models.DecimalField(decimal_places=4, max_digits=10)),
                ('y', models.DecimalField(decimal_places=4, max_digits=10)),
                ('z', models.DecimalField(decimal_places=4, max_digits=10)),
                ('width', models.DecimalField(decimal_places=4, max_digits=10)),
                ('height', models.DecimalField(decimal_places=4, max_digits=10)),
                ('depth', models.DecimalField(decimal_places=4, max_digits=10)),
                ('warehouse', models.ForeignKey(db_column='warehouse_id', on_delete=django.db.models.deletion.CASCADE, related_name='zones', to='warehouse.warehouse')),
            ],
            options={
                'db_table': 'zones',
            },
        ),
        migrations.CreateModel(
            name='ZoneBoundary',
            fields=[
                ('id', models.UUIDField(db_column='boundary_id', default=uuid.uuid4, primary_key=True, serialize=False)),
                ('polygon_points', models.JSONField(default=list)),
                ('zone', models.ForeignKey(db_column='zone_id', on_delete=django.db.models.deletion.CASCADE, related_name='boundaries', to='warehouse.zone')),
            ],
            options={
                'db_table': 'zone_boundaries',
            },
        ),
        migrations.CreateModel(
            name='WarehousePath',
            fields=[
                ('id', models.UUIDField(db_column='path_id', default=uuid.uuid4, primary_key=True, serialize=False)),
                ('path_name', models.CharField(max_length=100)),
                ('start_x', models.DecimalField(decimal_places=4, max_digits=10)),
                ('start_y', models.DecimalField(decimal_places=4, max_digits=10)),
                ('start_z', models.DecimalField(decimal_places=4, max_digits=10)),
                ('end_x', models.DecimalField(decimal_places=4, max_digits=10)),
                ('end_y', models.DecimalField(decimal_places=4, max_digits=10)),
                ('end_z', models.DecimalField(decimal_places=4, max_digits=10)),
                ('width', models.DecimalField(decimal_places=4, max_digits=10)),
                ('is_two_way', models.BooleanField(default=True)),
                ('warehouse', models.ForeignKey(db_column='warehouse_id', on_delete=django.db.models.deletion.CASCADE, related_name='paths', to='warehouse.warehouse')),
            ],
            options={
                'db_table': 'warehouse_paths',
            },
        ),
        migrations.CreateModel(
            name='WarehouseLayout',
            fields=[
                ('id', models.UUIDField(db_column='layout_id', default=uuid.uuid4, primary_key=True, serialize=False)),
                ('layout_name', models.CharField(max_length=100)),
                ('cad_file_url', models.TextField(blank=True, null=True)),
                ('width', models.DecimalField(decimal_places=2, max_digits=10)),
                ('height', models.DecimalField(decimal_places=2, max_digits=10)),
                ('depth', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('warehouse', models.ForeignKey(db_column='warehouse_id', on_delete=django.db.models.deletion.CASCADE, related_name='layouts', to='warehouse.warehouse')),
            ],
            options={
                'db_table': 'warehouse_layouts',
            },
        ),
        migrations.CreateModel(
            name='WarehouseHeatmap',
            fields=[
                ('id', models.UUIDField(db_column='heatmap_id', default=uuid.uuid4, primary_key=True, serialize=False)),
                ('activity_score', models.DecimalField(decimal_places=4, max_digits=5)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('zone', models.ForeignKey(db_column='zone_id', on_delete=django.db.models.deletion.CASCADE, related_name='heatmaps', to='warehouse.zone')),
            ],
            options={
                'db_table': 'warehouse_heatmaps',
            },
        ),
        migrations.CreateModel(
            name='StorageLocationNodeMap',
            fields=[
                ('id', models.UUIDField(db_column='map_id', default=uuid.uuid4, primary_key=True, serialize=False)),
                ('bin', models.OneToOneField(blank=True, db_column='bin_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='node_map', to='warehouse.bin')),
                ('navigation_node', models.ForeignKey(db_column='navigation_node_id', on_delete=django.db.models.deletion.CASCADE, related_name='location_maps', to='warehouse.navigationnode')),
                ('rack', models.OneToOneField(blank=True, db_column='rack_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='node_map', to='warehouse.rack')),
                ('shelf', models.OneToOneField(blank=True, db_column='shelf_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='node_map', to='warehouse.shelf')),
                ('warehouse', models.ForeignKey(db_column='warehouse_id', on_delete=django.db.models.deletion.CASCADE, related_name='location_node_maps', to='warehouse.warehouse')),
                ('zone', models.OneToOneField(blank=True, db_column='zone_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='node_map', to='warehouse.zone')),
            ],
            options={
                'db_table': 'storage_location_node_map',
            },
        ),
        migrations.CreateModel(
            name='SpatialEntity',
            fields=[
                ('id', models.UUIDField(db_column='entity_id', default=uuid.uuid4, primary_key=True, serialize=False)),
                ('entity_name', models.CharField(max_length=100)),
                ('entity_type', models.CharField(max_length=50)),
                ('x', models.DecimalField(decimal_places=4, max_digits=10)),
                ('y', models.DecimalField(decimal_places=4, max_digits=10)),
                ('z', models.DecimalField(decimal_places=4, max_digits=10)),
                ('width', models.DecimalField(decimal_places=4, max_digits=10)),
                ('height', models.DecimalField(decimal_places=4, max_digits=10)),
                ('depth', models.DecimalField(decimal_places=4, max_digits=10)),
                ('rotation_angle', models.DecimalField(decimal_places=4, default=0, max_digits=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('warehouse', models.ForeignKey(db_column='warehouse_id', on_delete=django.db.models.deletion.CASCADE, related_name='spatial_entities', to='warehouse.warehouse')),
            ],
            options={
                'db_table': 'spatial_entities',
            },
        ),
        migrations.CreateModel(
            name='RouteSegment',
            fields=[
                ('id', models.UUIDField(db_column='segment_id', default=uuid.uuid4, primary_key=True, serialize=False)),
                ('segment_order', models.IntegerField()),
                ('x', models.DecimalField(decimal_places=4, max_digits=10)),
                ('y', models.DecimalField(decimal_places=4, max_digits=10)),
                ('z', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segments', to='warehouse.optimizedroute')),
            ],
            options={
                'db_table': 'route_segments',
                'ordering': ['segment_order'],
            },
        ),
        migrations.CreateModel(
            name='RouteHistory',
            fields=[
                ('id', models.UUIDField(db_column='history_id', default=uuid.uuid4, primary_key=True, serialize=False)),
                ('executed_by', models.CharField(blank=True, max_length=100, null=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(default='PENDING', max_length=50)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='warehouse.optimizedroute')),
            ],
            options={
                'db_table': 'route_history',
            },
        ),
        migrations.CreateModel(
            name='RackCoordinate',
            fields=[
                ('id', models.UUIDField(db_column='coordinate_id', default=uuid.uuid4, primary_key=True, serialize=False)),
                ('access_point_x', models.DecimalField(decimal_places=4, max_digits=10)),
                ('access_point_y', models.DecimalField(decimal_places=4, max_digits=10)),
                ('access_point_z', models.DecimalField(decimal_places=4, max_digits=10)),
                ('side', models.CharField(max_length=50)),
                ('rack', models.ForeignKey(db_column='rack_id', on_delete=django.db.models.deletion.CASCADE, related_name='coordinates', to='warehouse.rack')),
            ],
            options={
                'db_table': 'rack_coordinates',
            },
        ),
        migrations.AddField(
            model_name='rack',
            name='zone',
            field=models.ForeignKey(db_column='zone_id', on_delete=django.db.models.deletion.CASCADE, related_name='racks', to='warehouse.zone'),
        ),
        migrations.AddField(
            model_name='optimizedroute',
            name='warehouse',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='optimized_routes', to='warehouse.warehouse'),
        ),
        migrations.AddField(
            model_name='navigationnode',
            name='warehouse',
            field=models.ForeignKey(db_column='warehouse_id', on_delete=django.db.models.deletion.CASCADE, related_name='navigation_nodes', to='warehouse.warehouse'),
        ),
        migrations.CreateModel(
            name='NavigationEdge',
            fields=[
                ('id', models.UUIDField(db_column='edge_id', default=uuid.uuid4, primary_key=True, serialize=False)),
                ('edge_weight', models.DecimalField(decimal_places=4, default=1.0, max_digits=10)),
                ('congestion_score', models.DecimalField(decimal_places=4, default=0.0, max_digits=5)),
                ('is_blocked', models.BooleanField(default=False)),
                ('travel_time', models.DecimalField(decimal_places=4, default=0.0, max_digits=10)),
                ('dynamic_cost', models.DecimalField(decimal_places=4, default=1.0, max_digits=10)),
                ('from_node', models.ForeignKey(db_column='from_node_id', on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_edges', to='warehouse.navigationnode')),
                ('to_node', models.ForeignKey(db_column='to_node_id', on_delete=django.db.models.deletion.CASCADE, related_name='incoming_edges', to='warehouse.navigationnode')),
                ('warehouse', models.ForeignKey(db_column='warehouse_id', on_delete=django.db.models.deletion.CASCADE, related_name='navigation_edges', to='warehouse.warehouse')),
            ],
            options={
                'db_table': 'navigation_edges',
            },
        ),
        migrations.CreateModel(
            name='MLExtraction',
            fields=[
                ('id', models.UUIDField(db_column='extraction_id', default=uuid.uuid4, primary_key=True, serialize=False)),
                ('extracted_data', models.JSONField()),
                ('model_version', models.CharField(max_length=50)),
                ('processed_at', models.DateTimeField(auto_now_add=True)),
                ('object', models.ForeignKey(db_column='object_id', on_delete=django.db.models.deletion.CASCADE, related_name='ml_extractions', to='warehouse.cadobject')),
            ],
            options={
                'db_table': 'ml_extractions',
            },
        ),
        migrations.AddField(
            model_name='cadobject',
            name='layout',
            field=models.ForeignKey(db_column='layout_id', on_delete=django.db.models.deletion.CASCADE, related_name='cad_objects', to='warehouse.warehouselayout'),
        ),
        migrations.AddField(
            model_name='bin',
            name='shelf',
            field=models.ForeignKey(db_column='shelf_id', on_delete=django.db.models.deletion.CASCADE, related_name='bins', to='warehouse.shelf'),
        ),
        migrations.AddConstraint(
            model_name='storagelocationnodemap',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('bin__isnull', False), ('rack__isnull', True), ('shelf__isnull', True), ('zone__isnull', True)), models.Q(('bin__isnull', True), ('rack__isnull', True), ('shelf__isnull', False), ('zone__isnull', True)), models.Q(('bin__isnull', True), ('rack__isnull', False), ('shelf__isnull', True), ('zone__isnull', True)), models.Q(('bin__isnull', True), ('rack__isnull', True), ('shelf__isnull', True), ('zone__isnull', False)), _connector='OR'), name='exactly_one_storage_fk'),
        ),
        migrations.AlterUniqueTogether(
            name='navigationedge',
            unique_together={('from_node', 'to_node')},
        ),
    ]
