# Generated by Django 4.2.30 on 2026-06-11 09:19

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZoneGroup',
            fields=[
                ('id', models.UUIDField(db_column='zone_group_id', default=uuid.uuid4, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('zone_group_type', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('warehouse', models.ForeignKey(db_column='warehouse_id', on_delete=django.db.models.deletion.CASCADE, related_name='zone_groups', to='warehouse.warehouse')),
            ],
            options={
                'db_table': 'zone_groups',
            },
        ),
        migrations.CreateModel(
            name='Aisle',
            fields=[
                ('id', models.UUIDField(db_column='aisle_id', default=uuid.uuid4, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('start_x', models.DecimalField(decimal_places=4, max_digits=10)),
                ('start_y', models.DecimalField(decimal_places=4, max_digits=10)),
                ('end_x', models.DecimalField(decimal_places=4, max_digits=10)),
                ('end_y', models.DecimalField(decimal_places=4, max_digits=10)),
                ('width', models.DecimalField(decimal_places=4, default=1.0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('zone', models.ForeignKey(db_column='zone_id', on_delete=django.db.models.deletion.CASCADE, related_name='aisles', to='warehouse.zone')),
            ],
            options={
                'db_table': 'aisles',
            },
        ),
        migrations.AddField(
            model_name='rack',
            name='aisle',
            field=models.ForeignKey(blank=True, db_column='aisle_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='racks', to='warehouse.aisle'),
        ),
        migrations.AddField(
            model_name='zone',
            name='zone_group',
            field=models.ForeignKey(blank=True, db_column='zone_group_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zones', to='warehouse.zonegroup'),
        ),
    ]
