# Generated by Django 4.2.30 on 2026-06-11 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0002_zonegroup_aisle_rack_aisle_zone_zone_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='bin',
            name='height',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='bin',
            name='length',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='bin',
            name='width',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
