# Generated by Django 5.1.1 on 2026-06-03 15:59

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocr', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ocrdocument',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='ocrdocument',
            name='document_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='ocrdocument',
            name='document_type',
            field=models.CharField(choices=[('invoice', 'Invoice'), ('po', 'Purchase Order'), ('manifest', 'Manifest'), ('other', 'Other')], default='other', max_length=50),
        ),
        migrations.AlterField(
            model_name='ocrdocument',
            name='extracted_text',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='ocrdocument',
            name='id',
            field=models.UUIDField(db_column='ocr_id', default=uuid.uuid4, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='ocrdocument',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20),
        ),
    ]
