# Generated by Django 4.2.30 on 2026-05-25 04:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OutboundShipment',
            fields=[
                ('id', models.UUIDField(db_column='outbound_id', default=uuid.uuid4, primary_key=True, serialize=False)),
                ('shipment_code', models.CharField(max_length=100, unique=True)),
                ('customer_name', models.CharField(max_length=200)),
                ('dispatch_time', models.DateTimeField()),
                ('status', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'outbound_shipments',
            },
        ),
    ]
