# Generated by Django 4.2.30 on 2026-05-25 04:43

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        ('bins', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StorageAllocation',
            fields=[
                ('id', models.UUIDField(db_column='allocation_id', default=uuid.uuid4, primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('allocated_at', models.DateTimeField(auto_now_add=True)),
                ('bin', models.ForeignKey(db_column='bin_id', on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='bins.bin')),
                ('product', models.ForeignKey(db_column='product_id', on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='products.product')),
            ],
            options={
                'db_table': 'storage_allocations',
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.UUIDField(db_column='movement_id', default=uuid.uuid4, primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('movement_type', models.CharField(max_length=50)),
                ('moved_at', models.DateTimeField(auto_now_add=True)),
                ('from_bin', models.ForeignKey(db_column='from_bin', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movements_from', to='bins.bin')),
                ('product', models.ForeignKey(db_column='product_id', on_delete=django.db.models.deletion.CASCADE, related_name='stock_movements', to='products.product')),
                ('to_bin', models.ForeignKey(db_column='to_bin', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movements_to', to='bins.bin')),
            ],
            options={
                'db_table': 'stock_movements',
            },
        ),
    ]
