# Generated by Django 4.2.30 on 2026-06-20 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='outboundshipment',
            name='items',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='outboundshipment',
            name='picklist',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='outboundshipment',
            name='dispatch_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
