# Generated by Django 4.2.30 on 2026-06-08 06:04

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InboundShipment',
            fields=[
                ('id', models.UUIDField(db_column='inbound_id', default=uuid.uuid4, primary_key=True, serialize=False)),
                ('shipment_code', models.CharField(max_length=100, unique=True)),
                ('supplier_name', models.CharField(max_length=200)),
                ('expected_arrival', models.DateTimeField()),
                ('status', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'inbound_shipments',
            },
        ),
        migrations.CreateModel(
            name='OCRDocument',
            fields=[
                ('id', models.UUIDField(db_column='ocr_id', default=uuid.uuid4, primary_key=True, serialize=False)),
                ('document_name', models.CharField(max_length=200)),
                ('document_type', models.CharField(choices=[('invoice', 'Invoice'), ('po', 'Purchase Order'), ('manifest', 'Manifest'), ('other', 'Other')], default='other', max_length=50)),
                ('document_url', models.URLField()),
                ('extracted_text', models.TextField(blank=True, default='')),
                ('structured_data', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'ocr_documents',
                'ordering': ['-created_at'],
            },
        ),
    ]
