# Generated by Django 4.2.30 on 2026-06-12 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inbound', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ocrdocument',
            old_name='structured_data',
            new_name='extracted_json',
        ),
        migrations.RenameField(
            model_name='ocrdocument',
            old_name='extracted_text',
            new_name='raw_text',
        ),
        migrations.RemoveField(
            model_name='ocrdocument',
            name='document_name',
        ),
        migrations.RemoveField(
            model_name='ocrdocument',
            name='document_url',
        ),
        migrations.RemoveField(
            model_name='ocrdocument',
            name='status',
        ),
        migrations.AddField(
            model_name='ocrdocument',
            name='confidence_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ocrdocument',
            name='document_hash',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='ocrdocument',
            name='file_name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ocrdocument',
            name='file_path',
            field=models.CharField(default='', max_length=512),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ocrdocument',
            name='processing_status',
            field=models.CharField(choices=[('UPLOADED', 'Uploaded'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('REVIEW_REQUIRED', 'Review Required')], default='UPLOADED', max_length=50),
        ),
        migrations.AlterField(
            model_name='ocrdocument',
            name='document_type',
            field=models.CharField(max_length=100),
        ),
    ]
