# Generated by Django 4.2.30 on 2026-06-15 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inbound', '0002_rename_structured_data_ocrdocument_extracted_json_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ocrdocument',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ocrdocument',
            name='processing_status',
            field=models.CharField(choices=[('UPLOADED', 'Uploaded'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('REVIEW_REQUIRED', 'Review Required'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='UPLOADED', max_length=50),
        ),
    ]
