# Generated by Django 4.2.30 on 2026-06-23 06:24

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_stockmovement_operator'),
        ('warehouse', '0003_bin_dimensions'),
        ('inbound', '0003_ocrdocument_rejection_reason_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InboundShipmentLine',
            fields=[
                ('id', models.UUIDField(db_column='line_id', default=uuid.uuid4, primary_key=True, serialize=False)),
                ('sku', models.CharField(max_length=100)),
                ('product_name', models.CharField(max_length=200)),
                ('quantity', models.IntegerField()),
                ('weight', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('dimensions', models.CharField(default='10x8x6 cm', max_length=100)),
                ('storage_type', models.CharField(default='GENERAL', max_length=50)),
                ('recommendation_status', models.CharField(default='WAITING_FOR_BIN_ASSIGNMENT', max_length=50)),
                ('product', models.ForeignKey(blank=True, db_column='product_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inbound_lines', to='inventory.product')),
            ],
            options={
                'db_table': 'inbound_shipment_lines',
            },
        ),
        migrations.AddField(
            model_name='inboundshipment',
            name='ocr_document',
            field=models.ForeignKey(blank=True, db_column='ocr_document_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipments', to='inbound.ocrdocument'),
        ),
        migrations.CreateModel(
            name='PutawayTask',
            fields=[
                ('id', models.UUIDField(db_column='task_id', default=uuid.uuid4, primary_key=True, serialize=False)),
                ('operator', models.CharField(blank=True, max_length=150, null=True)),
                ('quantity', models.IntegerField()),
                ('source_dock', models.CharField(default='Receiving Dock', max_length=100)),
                ('status', models.CharField(choices=[('ASSIGNED', 'Assigned'), ('IN_PROGRESS', 'In Progress'), ('PICKED_FROM_RECEIVING', 'Picked From Receiving'), ('REACHED_BIN', 'Reached Bin'), ('COMPLETED', 'Completed'), ('DELAYED', 'Delayed')], default='ASSIGNED', max_length=50)),
                ('issue_type', models.CharField(blank=True, max_length=100, null=True)),
                ('issue_description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('destination_bin', models.ForeignKey(db_column='bin_id', on_delete=django.db.models.deletion.CASCADE, related_name='putaway_tasks', to='warehouse.bin')),
                ('inbound_line', models.ForeignKey(blank=True, db_column='line_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='putaway_tasks', to='inbound.inboundshipmentline')),
                ('inbound_shipment', models.ForeignKey(blank=True, db_column='inbound_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='putaway_tasks', to='inbound.inboundshipment')),
                ('product', models.ForeignKey(db_column='product_id', on_delete=django.db.models.deletion.CASCADE, related_name='putaway_tasks', to='inventory.product')),
            ],
            options={
                'db_table': 'putaway_tasks',
            },
        ),
        migrations.AddField(
            model_name='inboundshipmentline',
            name='shipment',
            field=models.ForeignKey(db_column='shipment_id', on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='inbound.inboundshipment'),
        ),
    ]
