# Generated by Django 4.2.30 on 2026-06-25 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inbound', '0004_ocrdocument_bin_ocrdocument_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ocrdocument',
            name='rag_error_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ocrdocument',
            name='rag_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('INGESTING', 'Ingesting'), ('INGESTED', 'Ingested'), ('FAILED', 'Failed')], default='PENDING', max_length=50),
        ),
    ]
