# Generated by Django 4.2.30 on 2026-06-29 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inbound', '0004_inboundshipmentline_inboundshipment_ocr_document_and_more'),
        ('inbound', '0005_ocrdocument_rag_error_message_ocrdocument_rag_status'),
    ]

    operations = [
    ]
