# Generated by Django 4.2.30 on 2026-06-29 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inbound', '0006_merge_20260629_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ocrdocument',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='ocrdocument',
            name='document_hash',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='ocrdocument',
            name='document_type',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='ocrdocument',
            name='processing_status',
            field=models.CharField(choices=[('UPLOADED', 'Uploaded'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('REVIEW_REQUIRED', 'Review Required'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], db_index=True, default='UPLOADED', max_length=50),
        ),
    ]
