# Generated by Django 4.2.30 on 2026-05-25 05:21

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('warehouses', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OptimizedRoute',
            fields=[
                ('id', models.UUIDField(db_column='route_id', default=uuid.uuid4, primary_key=True, serialize=False)),
                ('start_location', models.CharField(max_length=100)),
                ('distance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estimated_time', models.IntegerField(help_text='Estimated time in seconds')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('warehouse', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='optimized_routes', to='warehouses.warehouse')),
            ],
            options={
                'db_table': 'optimized_routes',
            },
        ),
        migrations.CreateModel(
            name='RouteSegment',
            fields=[
                ('id', models.UUIDField(db_column='segment_id', default=uuid.uuid4, primary_key=True, serialize=False)),
                ('segment_order', models.IntegerField()),
                ('x', models.DecimalField(decimal_places=4, max_digits=10)),
                ('y', models.DecimalField(decimal_places=4, max_digits=10)),
                ('z', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segments', to='routes.optimizedroute')),
            ],
            options={
                'db_table': 'route_segments',
                'ordering': ['segment_order'],
            },
        ),
        migrations.CreateModel(
            name='RouteHistory',
            fields=[
                ('id', models.UUIDField(db_column='history_id', default=uuid.uuid4, primary_key=True, serialize=False)),
                ('executed_by', models.CharField(blank=True, max_length=100, null=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(default='PENDING', max_length=50)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='routes.optimizedroute')),
            ],
            options={
                'db_table': 'route_history',
            },
        ),
    ]
