# Generated by Django 5.1.1 on 2026-06-02 08:40

import uuid
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bins', '0002_initial'),
        ('routes', '0001_initial'),
        ('warehouses', '0003_navigationedge'),
        ('zones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StorageLocationNodeMap',
            fields=[
                ('id', models.UUIDField(db_column='map_id', default=uuid.uuid4, primary_key=True, serialize=False)),
                ('bin', models.OneToOneField(blank=True, db_column='bin_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='node_map', to='bins.bin')),
                ('shelf', models.OneToOneField(blank=True, db_column='shelf_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='node_map', to='bins.shelf')),
                ('rack', models.OneToOneField(blank=True, db_column='rack_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='node_map', to='warehouses.rack')),
                ('zone', models.OneToOneField(blank=True, db_column='zone_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='node_map', to='zones.zone')),
                ('warehouse', models.ForeignKey(db_column='warehouse_id', on_delete=django.db.models.deletion.CASCADE, related_name='location_node_maps', to='warehouses.warehouse')),
                ('navigation_node', models.ForeignKey(db_column='navigation_node_id', on_delete=django.db.models.deletion.CASCADE, related_name='location_maps', to='warehouses.navigationnode')),
            ],
            options={
                'db_table': 'storage_location_node_map',
                'constraints': [
                    models.CheckConstraint(
                        check=(
                            models.Q(bin__isnull=False, shelf__isnull=True, rack__isnull=True, zone__isnull=True) |
                            models.Q(bin__isnull=True, shelf__isnull=False, rack__isnull=True, zone__isnull=True) |
                            models.Q(bin__isnull=True, shelf__isnull=True, rack__isnull=False, zone__isnull=True) |
                            models.Q(bin__isnull=True, shelf__isnull=True, rack__isnull=True, zone__isnull=False)
                        ),
                        name='exactly_one_storage_fk',
                    ),
                ],
            },
        ),
    ]
