# Generated by Django 4.2.30 on 2026-05-25 04:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RobotTask',
            fields=[
                ('id', models.UUIDField(db_column='task_id', default=uuid.uuid4, primary_key=True, serialize=False)),
                ('task_type', models.CharField(max_length=100)),
                ('source_location', models.CharField(max_length=100)),
                ('destination_location', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'robot_tasks',
            },
        ),
        migrations.CreateModel(
            name='RouteOptimization',
            fields=[
                ('id', models.UUIDField(db_column='route_id', default=uuid.uuid4, primary_key=True, serialize=False)),
                ('source_location', models.CharField(max_length=100)),
                ('destination_location', models.CharField(max_length=100)),
                ('optimized_path', models.JSONField()),
                ('estimated_time', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'route_optimizations',
            },
        ),
    ]
