# Generated by Django 4.2.30 on 2026-05-25 04:43

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        ('bins', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIModel',
            fields=[
                ('id', models.UUIDField(db_column='model_id', default=uuid.uuid4, primary_key=True, serialize=False)),
                ('model_name', models.CharField(max_length=100)),
                ('model_version', models.CharField(max_length=50)),
                ('accuracy', models.DecimalField(decimal_places=4, max_digits=5)),
                ('deployed_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'ai_models',
            },
        ),
        migrations.CreateModel(
            name='AllocationRecommendation',
            fields=[
                ('id', models.UUIDField(db_column='recommendation_id', default=uuid.uuid4, primary_key=True, serialize=False)),
                ('confidence_score', models.DecimalField(decimal_places=4, max_digits=5)),
                ('reasoning', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(db_column='product_id', on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='products.product')),
                ('recommended_bin', models.ForeignKey(db_column='recommended_bin', on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='bins.bin')),
            ],
            options={
                'db_table': 'allocation_recommendations',
            },
        ),
        migrations.CreateModel(
            name='AIPrediction',
            fields=[
                ('id', models.UUIDField(db_column='prediction_id', default=uuid.uuid4, primary_key=True, serialize=False)),
                ('prediction_type', models.CharField(max_length=100)),
                ('prediction_result', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('model', models.ForeignKey(db_column='model_id', on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to='recommendations.aimodel')),
            ],
            options={
                'db_table': 'ai_predictions',
            },
        ),
    ]
