# Generated by Django 4.2.30 on 2026-05-25 05:57

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('bins', '0002_initial'),
        ('zones', '0001_initial'),
        ('recommendations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIDecision',
            fields=[
                ('id', models.UUIDField(db_column='decision_id', default=uuid.uuid4, primary_key=True, serialize=False)),
                ('decision_type', models.CharField(max_length=100)),
                ('input_features', models.JSONField(default=dict)),
                ('decision_output', models.JSONField(default=dict)),
                ('feedback_received', models.JSONField(blank=True, null=True)),
                ('executed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'ai_decisions',
            },
        ),
        migrations.CreateModel(
            name='SlottingScore',
            fields=[
                ('id', models.UUIDField(db_column='score_id', default=uuid.uuid4, primary_key=True, serialize=False)),
                ('score', models.DecimalField(decimal_places=4, max_digits=10)),
                ('congestion_penalty', models.DecimalField(decimal_places=4, default=0.0, max_digits=10)),
                ('travel_cost', models.DecimalField(decimal_places=4, default=0.0, max_digits=10)),
                ('affinity_bonus', models.DecimalField(decimal_places=4, default=0.0, max_digits=10)),
                ('calculated_at', models.DateTimeField(auto_now_add=True)),
                ('bin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bins.bin')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
            options={
                'db_table': 'slotting_scores',
            },
        ),
        migrations.CreateModel(
            name='SlottingHistory',
            fields=[
                ('id', models.UUIDField(db_column='history_id', default=uuid.uuid4, primary_key=True, serialize=False)),
                ('moved_at', models.DateTimeField(auto_now_add=True)),
                ('pick_time_seconds', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('efficiency_gain', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
                ('source_bin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='slotting_source_history', to='bins.bin')),
                ('target_bin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slotting_target_history', to='bins.bin')),
            ],
            options={
                'db_table': 'slotting_history',
            },
        ),
        migrations.CreateModel(
            name='DemandForecast',
            fields=[
                ('id', models.UUIDField(db_column='forecast_id', default=uuid.uuid4, primary_key=True, serialize=False)),
                ('predicted_demand_score', models.DecimalField(decimal_places=4, max_digits=5)),
                ('forecast_period', models.CharField(default='DAILY', max_length=50)),
                ('confidence_score', models.DecimalField(decimal_places=4, default=0.9, max_digits=5)),
                ('forecasted_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demand_forecasts', to='products.product')),
            ],
            options={
                'db_table': 'demand_forecasts',
            },
        ),
        migrations.CreateModel(
            name='CongestionPrediction',
            fields=[
                ('id', models.UUIDField(db_column='prediction_id', default=uuid.uuid4, primary_key=True, serialize=False)),
                ('congestion_risk', models.DecimalField(decimal_places=4, max_digits=5)),
                ('predicted_traffic_volume', models.IntegerField(default=0)),
                ('predicted_at', models.DateTimeField(auto_now_add=True)),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='congestion_predictions', to='zones.zone')),
            ],
            options={
                'db_table': 'congestion_predictions',
            },
        ),
    ]
