# Generated by Django 4.2.30 on 2026-06-11 11:49

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0003_bin_dimensions'),
        ('inventory', '0001_initial'),
        ('recommendations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productclassification',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='recommendationrule',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='recommendationrule',
            name='priority',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='storagerecommendation',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='BinAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allocation_score', models.FloatField()),
                ('allocation_reason', models.TextField()),
                ('allocation_source', models.CharField(choices=[('RULE_ENGINE', 'Rule Engine')], default='RULE_ENGINE', max_length=20)),
                ('allocation_version', models.CharField(default='v1', max_length=10)),
                ('selected_orientation', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bin', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bin_allocations', to='warehouse.bin')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bin_allocations', to='inventory.product')),
                ('rack', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bin_allocations', to='warehouse.rack')),
                ('shelf', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bin_allocations', to='warehouse.shelf')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bin_allocations', to='warehouse.zone')),
                ('zone_group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bin_allocations', to='warehouse.zonegroup')),
            ],
            options={
                'db_table': 'bin_allocations',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['product', 'zone', 'bin'], name='bin_alloc_query_idx')],
            },
        ),
    ]
