# Generated by Django 4.2.30 on 2026-05-25 07:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0002_aidecision_slottingscore_slottinghistory_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemAlert',
            fields=[
                ('id', models.UUIDField(db_column='alert_id', default=uuid.uuid4, primary_key=True, serialize=False)),
                ('alert_type', models.CharField(max_length=50)),
                ('zone_code', models.CharField(blank=True, max_length=50, null=True)),
                ('severity', models.CharField(default='INFO', max_length=20)),
                ('message', models.TextField()),
                ('is_resolved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'system_alerts',
            },
        ),
    ]
