# Generated by Django 4.2.30 on 2026-06-11 12:07

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0003_binallocation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bin3DPlacement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occupied_volume', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('remaining_volume', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('utilization_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('placement_strategy', models.CharField(choices=[('BOTTOM_FLAT', 'Bottom Flat'), ('STACKED', 'Stacked'), ('CORNER_ALIGN', 'Corner Aligned')], default='BOTTOM_FLAT', max_length=20)),
                ('label_direction', models.CharField(choices=[('FRONT', 'Facing Front'), ('TOP', 'Facing Top'), ('SIDE', 'Facing Side')], default='FRONT', max_length=20)),
                ('position_x', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('position_y', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('position_z', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('bin_allocation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='placement_3d', to='recommendations.binallocation')),
            ],
            options={
                'db_table': 'bin_3d_placements',
                'ordering': ['-created_at'],
            },
        ),
    ]
