# Generated by Django 4.2.30 on 2026-06-13 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0004_bin3dplacement'),
    ]

    operations = [
        migrations.AddField(
            model_name='binallocation',
            name='navigation_instructions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='binallocation',
            name='placement_instructions',
            field=models.TextField(blank=True, null=True),
        ),
    ]
