# Generated by Django 4.2.30 on 2026-06-15 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0005_binallocation_navigation_instructions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='binallocation',
            name='operator',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='binallocation',
            name='storage_status',
            field=models.CharField(choices=[('ALLOCATED', 'Allocated'), ('IN_PROGRESS', 'In Progress'), ('STORED', 'Stored')], default='ALLOCATED', max_length=20),
        ),
        migrations.AddField(
            model_name='binallocation',
            name='stored_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
