# Generated by Django 4.2.30 on 2026-06-23 06:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inbound', '0004_inboundshipmentline_inboundshipment_ocr_document_and_more'),
        ('recommendations', '0006_binallocation_operator_binallocation_storage_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='binallocation',
            name='inbound_line',
            field=models.ForeignKey(blank=True, db_column='inbound_line_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bin_allocations', to='inbound.inboundshipmentline'),
        ),
        migrations.AddField(
            model_name='binallocation',
            name='inbound_shipment',
            field=models.ForeignKey(blank=True, db_column='inbound_shipment_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bin_allocations', to='inbound.inboundshipment'),
        ),
    ]
