# Generated by Django 4.2.30 on 2026-06-25 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0007_binallocation_inbound_line_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='binallocation',
            name='max_units',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='binallocation',
            name='utilization_score',
            field=models.FloatField(default=0.0),
        ),
    ]
