# Generated by Django 4.2.30 on 2026-06-08 06:04

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AIDecision',
            fields=[
                ('id', models.UUIDField(db_column='decision_id', default=uuid.uuid4, primary_key=True, serialize=False)),
                ('decision_type', models.CharField(max_length=100)),
                ('input_features', models.JSONField(default=dict)),
                ('decision_output', models.JSONField(default=dict)),
                ('feedback_received', models.JSONField(blank=True, null=True)),
                ('executed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'ai_decisions',
            },
        ),
        migrations.CreateModel(
            name='AIModel',
            fields=[
                ('id', models.UUIDField(db_column='model_id', default=uuid.uuid4, primary_key=True, serialize=False)),
                ('model_name', models.CharField(max_length=100)),
                ('model_version', models.CharField(max_length=50)),
                ('accuracy', models.DecimalField(decimal_places=4, max_digits=5)),
                ('deployed_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'ai_models',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(db_column='product_id', default=uuid.uuid4, primary_key=True, serialize=False)),
                ('sku', models.CharField(max_length=100, unique=True)),
                ('product_name', models.CharField(max_length=200)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_fragile', models.BooleanField(default=False)),
                ('is_hazardous', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'products',
            },
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.UUIDField(db_column='category_id', default=uuid.uuid4, primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'product_categories',
            },
        ),
        migrations.CreateModel(
            name='RobotTask',
            fields=[
                ('id', models.UUIDField(db_column='task_id', default=uuid.uuid4, primary_key=True, serialize=False)),
                ('task_type', models.CharField(max_length=100)),
                ('source_location', models.CharField(max_length=100)),
                ('destination_location', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'robot_tasks',
            },
        ),
        migrations.CreateModel(
            name='RouteOptimization',
            fields=[
                ('id', models.UUIDField(db_column='route_id', default=uuid.uuid4, primary_key=True, serialize=False)),
                ('source_location', models.CharField(max_length=100)),
                ('destination_location', models.CharField(max_length=100)),
                ('optimized_path', models.JSONField()),
                ('estimated_time', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'route_optimizations',
            },
        ),
        migrations.CreateModel(
            name='SystemAlert',
            fields=[
                ('id', models.UUIDField(db_column='alert_id', default=uuid.uuid4, primary_key=True, serialize=False)),
                ('alert_type', models.CharField(max_length=50)),
                ('zone_code', models.CharField(blank=True, max_length=50, null=True)),
                ('severity', models.CharField(default='INFO', max_length=20)),
                ('message', models.TextField()),
                ('is_resolved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'system_alerts',
            },
        ),
        migrations.CreateModel(
            name='StorageAllocation',
            fields=[
                ('id', models.UUIDField(db_column='allocation_id', default=uuid.uuid4, primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('allocated_at', models.DateTimeField(auto_now_add=True)),
                ('bin', models.ForeignKey(db_column='bin_id', on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='warehouse.bin')),
                ('product', models.ForeignKey(db_column='product_id', on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='inventory.product')),
            ],
            options={
                'db_table': 'storage_allocations',
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.UUIDField(db_column='movement_id', default=uuid.uuid4, primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('movement_type', models.CharField(max_length=50)),
                ('moved_at', models.DateTimeField(auto_now_add=True)),
                ('from_bin', models.ForeignKey(db_column='from_bin', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movements_from', to='warehouse.bin')),
                ('product', models.ForeignKey(db_column='product_id', on_delete=django.db.models.deletion.CASCADE, related_name='stock_movements', to='inventory.product')),
                ('to_bin', models.ForeignKey(db_column='to_bin', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movements_to', to='warehouse.bin')),
            ],
            options={
                'db_table': 'stock_movements',
            },
        ),
        migrations.CreateModel(
            name='SlottingScore',
            fields=[
                ('id', models.UUIDField(db_column='score_id', default=uuid.uuid4, primary_key=True, serialize=False)),
                ('score', models.DecimalField(decimal_places=4, max_digits=10)),
                ('congestion_penalty', models.DecimalField(decimal_places=4, default=0.0, max_digits=10)),
                ('travel_cost', models.DecimalField(decimal_places=4, default=0.0, max_digits=10)),
                ('affinity_bonus', models.DecimalField(decimal_places=4, default=0.0, max_digits=10)),
                ('calculated_at', models.DateTimeField(auto_now_add=True)),
                ('bin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.bin')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.product')),
            ],
            options={
                'db_table': 'slotting_scores',
            },
        ),
        migrations.CreateModel(
            name='SlottingHistory',
            fields=[
                ('id', models.UUIDField(db_column='history_id', default=uuid.uuid4, primary_key=True, serialize=False)),
                ('moved_at', models.DateTimeField(auto_now_add=True)),
                ('pick_time_seconds', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('efficiency_gain', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.product')),
                ('source_bin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='slotting_source_history', to='warehouse.bin')),
                ('target_bin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slotting_target_history', to='warehouse.bin')),
            ],
            options={
                'db_table': 'slotting_history',
            },
        ),
        migrations.CreateModel(
            name='ProductStorageRule',
            fields=[
                ('id', models.UUIDField(db_column='rule_id', default=uuid.uuid4, primary_key=True, serialize=False)),
                ('allowed_zone_type', models.CharField(max_length=50)),
                ('max_stack_height', models.IntegerField()),
                ('required_temperature', models.DecimalField(decimal_places=2, max_digits=5)),
                ('orientation_rule', models.CharField(max_length=100)),
                ('product', models.ForeignKey(db_column='product_id', on_delete=django.db.models.deletion.CASCADE, related_name='storage_rules', to='inventory.product')),
            ],
            options={
                'db_table': 'product_storage_rules',
            },
        ),
        migrations.CreateModel(
            name='ProductDimension',
            fields=[
                ('id', models.UUIDField(db_column='dimension_id', default=uuid.uuid4, primary_key=True, serialize=False)),
                ('length', models.DecimalField(decimal_places=2, max_digits=10)),
                ('width', models.DecimalField(decimal_places=2, max_digits=10)),
                ('height', models.DecimalField(decimal_places=2, max_digits=10)),
                ('box_length', models.DecimalField(decimal_places=2, max_digits=10)),
                ('box_width', models.DecimalField(decimal_places=2, max_digits=10)),
                ('box_height', models.DecimalField(decimal_places=2, max_digits=10)),
                ('product', models.ForeignKey(db_column='product_id', on_delete=django.db.models.deletion.CASCADE, related_name='dimensions', to='inventory.product')),
            ],
            options={
                'db_table': 'product_dimensions',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(db_column='category_id', on_delete=django.db.models.deletion.CASCADE, related_name='products', to='inventory.productcategory'),
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.UUIDField(db_column='inventory_id', default=uuid.uuid4, primary_key=True, serialize=False)),
                ('total_quantity', models.IntegerField(default=0)),
                ('reserved_quantity', models.IntegerField(default=0)),
                ('damaged_quantity', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(db_column='product_id', on_delete=django.db.models.deletion.CASCADE, related_name='inventory_records', to='inventory.product')),
            ],
            options={
                'db_table': 'inventory',
            },
        ),
        migrations.CreateModel(
            name='DemandForecast',
            fields=[
                ('id', models.UUIDField(db_column='forecast_id', default=uuid.uuid4, primary_key=True, serialize=False)),
                ('predicted_demand_score', models.DecimalField(decimal_places=4, max_digits=5)),
                ('forecast_period', models.CharField(default='DAILY', max_length=50)),
                ('confidence_score', models.DecimalField(decimal_places=4, default=0.9, max_digits=5)),
                ('forecasted_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demand_forecasts', to='inventory.product')),
            ],
            options={
                'db_table': 'demand_forecasts',
            },
        ),
        migrations.CreateModel(
            name='CongestionPrediction',
            fields=[
                ('id', models.UUIDField(db_column='prediction_id', default=uuid.uuid4, primary_key=True, serialize=False)),
                ('congestion_risk', models.DecimalField(decimal_places=4, max_digits=5)),
                ('predicted_traffic_volume', models.IntegerField(default=0)),
                ('predicted_at', models.DateTimeField(auto_now_add=True)),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='congestion_predictions', to='warehouse.zone')),
            ],
            options={
                'db_table': 'congestion_predictions',
            },
        ),
        migrations.CreateModel(
            name='AllocationRecommendation',
            fields=[
                ('id', models.UUIDField(db_column='recommendation_id', default=uuid.uuid4, primary_key=True, serialize=False)),
                ('confidence_score', models.DecimalField(decimal_places=4, max_digits=5)),
                ('reasoning', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(db_column='product_id', on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='inventory.product')),
                ('recommended_bin', models.ForeignKey(db_column='recommended_bin', on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='warehouse.bin')),
            ],
            options={
                'db_table': 'allocation_recommendations',
            },
        ),
        migrations.CreateModel(
            name='AIPrediction',
            fields=[
                ('id', models.UUIDField(db_column='prediction_id', default=uuid.uuid4, primary_key=True, serialize=False)),
                ('prediction_type', models.CharField(max_length=100)),
                ('prediction_result', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('model', models.ForeignKey(db_column='model_id', on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to='inventory.aimodel')),
            ],
            options={
                'db_table': 'ai_predictions',
            },
        ),
    ]
