# Generated by Django 4.2.30 on 2026-05-25 04:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bin',
            fields=[
                ('id', models.UUIDField(db_column='bin_id', default=uuid.uuid4, primary_key=True, serialize=False)),
                ('bin_code', models.CharField(max_length=50, unique=True)),
                ('max_capacity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('current_capacity', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_occupied', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'bins',
            },
        ),
        migrations.CreateModel(
            name='Shelf',
            fields=[
                ('id', models.UUIDField(db_column='shelf_id', default=uuid.uuid4, primary_key=True, serialize=False)),
                ('shelf_number', models.IntegerField()),
                ('max_weight', models.DecimalField(decimal_places=2, max_digits=10)),
                ('height_from_ground', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'shelves',
            },
        ),
    ]
