# Generated by Django 4.2.30 on 2026-05-25 04:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('warehouses', '0001_initial'),
        ('bins', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shelf',
            name='rack',
            field=models.ForeignKey(db_column='rack_id', on_delete=django.db.models.deletion.CASCADE, related_name='shelves', to='warehouses.rack'),
        ),
        migrations.AddField(
            model_name='bin',
            name='shelf',
            field=models.ForeignKey(db_column='shelf_id', on_delete=django.db.models.deletion.CASCADE, related_name='bins', to='bins.shelf'),
        ),
    ]
