# Generated by Django 4.2.30 on 2026-05-25 04:43

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('warehouses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.UUIDField(db_column='zone_id', default=uuid.uuid4, primary_key=True, serialize=False)),
                ('zone_name', models.CharField(max_length=100)),
                ('zone_type', models.CharField(max_length=50)),
                ('x', models.DecimalField(decimal_places=4, max_digits=10)),
                ('y', models.DecimalField(decimal_places=4, max_digits=10)),
                ('z', models.DecimalField(decimal_places=4, max_digits=10)),
                ('width', models.DecimalField(decimal_places=4, max_digits=10)),
                ('height', models.DecimalField(decimal_places=4, max_digits=10)),
                ('depth', models.DecimalField(decimal_places=4, max_digits=10)),
                ('warehouse', models.ForeignKey(db_column='warehouse_id', on_delete=django.db.models.deletion.CASCADE, related_name='zones', to='warehouses.warehouse')),
            ],
            options={
                'db_table': 'zones',
            },
        ),
        migrations.CreateModel(
            name='ZoneBoundary',
            fields=[
                ('id', models.UUIDField(db_column='boundary_id', default=uuid.uuid4, primary_key=True, serialize=False)),
                ('polygon_points', models.JSONField(default=list)),
                ('zone', models.ForeignKey(db_column='zone_id', on_delete=django.db.models.deletion.CASCADE, related_name='boundaries', to='zones.zone')),
            ],
            options={
                'db_table': 'zone_boundaries',
            },
        ),
        migrations.CreateModel(
            name='WarehouseHeatmap',
            fields=[
                ('id', models.UUIDField(db_column='heatmap_id', default=uuid.uuid4, primary_key=True, serialize=False)),
                ('activity_score', models.DecimalField(decimal_places=4, max_digits=5)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('zone', models.ForeignKey(db_column='zone_id', on_delete=django.db.models.deletion.CASCADE, related_name='heatmaps', to='zones.zone')),
            ],
            options={
                'db_table': 'warehouse_heatmaps',
            },
        ),
    ]
