# Generated by Django 4.2.30 on 2026-05-25 04:43

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CADObject',
            fields=[
                ('id', models.UUIDField(db_column='object_id', default=uuid.uuid4, primary_key=True, serialize=False)),
                ('object_type', models.CharField(max_length=50)),
                ('detected_label', models.CharField(max_length=100)),
                ('confidence_score', models.DecimalField(decimal_places=4, max_digits=5)),
                ('x', models.DecimalField(decimal_places=4, max_digits=10)),
                ('y', models.DecimalField(decimal_places=4, max_digits=10)),
                ('z', models.DecimalField(decimal_places=4, max_digits=10)),
                ('width', models.DecimalField(decimal_places=4, max_digits=10)),
                ('height', models.DecimalField(decimal_places=4, max_digits=10)),
                ('depth', models.DecimalField(decimal_places=4, max_digits=10)),
            ],
            options={
                'db_table': 'cad_objects',
            },
        ),
        migrations.CreateModel(
            name='MLExtraction',
            fields=[
                ('id', models.UUIDField(db_column='extraction_id', default=uuid.uuid4, primary_key=True, serialize=False)),
                ('extracted_data', models.JSONField()),
                ('model_version', models.CharField(max_length=50)),
                ('processed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'ml_extractions',
            },
        ),
        migrations.CreateModel(
            name='NavigationNode',
            fields=[
                ('id', models.UUIDField(db_column='node_id', default=uuid.uuid4, primary_key=True, serialize=False)),
                ('node_name', models.CharField(max_length=100)),
                ('node_type', models.CharField(max_length=50)),
                ('x', models.DecimalField(decimal_places=4, max_digits=10)),
                ('y', models.DecimalField(decimal_places=4, max_digits=10)),
                ('z', models.DecimalField(decimal_places=4, max_digits=10)),
                ('connections', models.JSONField(blank=True, default=list)),
            ],
            options={
                'db_table': 'navigation_graph',
            },
        ),
        migrations.CreateModel(
            name='Rack',
            fields=[
                ('id', models.UUIDField(db_column='rack_id', default=uuid.uuid4, primary_key=True, serialize=False)),
                ('rack_code', models.CharField(max_length=50, unique=True)),
                ('max_weight', models.DecimalField(decimal_places=2, max_digits=10)),
                ('x', models.DecimalField(decimal_places=4, max_digits=10)),
                ('y', models.DecimalField(decimal_places=4, max_digits=10)),
                ('z', models.DecimalField(decimal_places=4, max_digits=10)),
                ('width', models.DecimalField(decimal_places=4, max_digits=10)),
                ('height', models.DecimalField(decimal_places=4, max_digits=10)),
                ('depth', models.DecimalField(decimal_places=4, max_digits=10)),
                ('rotation_angle', models.DecimalField(decimal_places=4, max_digits=8)),
            ],
            options={
                'db_table': 'racks',
            },
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.UUIDField(db_column='warehouse_id', default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('location', models.TextField(blank=True, null=True)),
                ('total_area_sqft', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'warehouses',
            },
        ),
        migrations.CreateModel(
            name='WarehousePath',
            fields=[
                ('id', models.UUIDField(db_column='path_id', default=uuid.uuid4, primary_key=True, serialize=False)),
                ('path_name', models.CharField(max_length=100)),
                ('start_x', models.DecimalField(decimal_places=4, max_digits=10)),
                ('start_y', models.DecimalField(decimal_places=4, max_digits=10)),
                ('start_z', models.DecimalField(decimal_places=4, max_digits=10)),
                ('end_x', models.DecimalField(decimal_places=4, max_digits=10)),
                ('end_y', models.DecimalField(decimal_places=4, max_digits=10)),
                ('end_z', models.DecimalField(decimal_places=4, max_digits=10)),
                ('width', models.DecimalField(decimal_places=4, max_digits=10)),
                ('is_two_way', models.BooleanField(default=True)),
                ('warehouse', models.ForeignKey(db_column='warehouse_id', on_delete=django.db.models.deletion.CASCADE, related_name='paths', to='warehouses.warehouse')),
            ],
            options={
                'db_table': 'warehouse_paths',
            },
        ),
        migrations.CreateModel(
            name='WarehouseLayout',
            fields=[
                ('id', models.UUIDField(db_column='layout_id', default=uuid.uuid4, primary_key=True, serialize=False)),
                ('layout_name', models.CharField(max_length=100)),
                ('cad_file_url', models.TextField(blank=True, null=True)),
                ('width', models.DecimalField(decimal_places=2, max_digits=10)),
                ('height', models.DecimalField(decimal_places=2, max_digits=10)),
                ('depth', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('warehouse', models.ForeignKey(db_column='warehouse_id', on_delete=django.db.models.deletion.CASCADE, related_name='layouts', to='warehouses.warehouse')),
            ],
            options={
                'db_table': 'warehouse_layouts',
            },
        ),
        migrations.CreateModel(
            name='SpatialEntity',
            fields=[
                ('id', models.UUIDField(db_column='entity_id', default=uuid.uuid4, primary_key=True, serialize=False)),
                ('entity_name', models.CharField(max_length=100)),
                ('entity_type', models.CharField(max_length=50)),
                ('x', models.DecimalField(decimal_places=4, max_digits=10)),
                ('y', models.DecimalField(decimal_places=4, max_digits=10)),
                ('z', models.DecimalField(decimal_places=4, max_digits=10)),
                ('width', models.DecimalField(decimal_places=4, max_digits=10)),
                ('height', models.DecimalField(decimal_places=4, max_digits=10)),
                ('depth', models.DecimalField(decimal_places=4, max_digits=10)),
                ('rotation_angle', models.DecimalField(decimal_places=4, default=0, max_digits=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('warehouse', models.ForeignKey(db_column='warehouse_id', on_delete=django.db.models.deletion.CASCADE, related_name='spatial_entities', to='warehouses.warehouse')),
            ],
            options={
                'db_table': 'spatial_entities',
            },
        ),
        migrations.CreateModel(
            name='RackCoordinate',
            fields=[
                ('id', models.UUIDField(db_column='coordinate_id', default=uuid.uuid4, primary_key=True, serialize=False)),
                ('access_point_x', models.DecimalField(decimal_places=4, max_digits=10)),
                ('access_point_y', models.DecimalField(decimal_places=4, max_digits=10)),
                ('access_point_z', models.DecimalField(decimal_places=4, max_digits=10)),
                ('side', models.CharField(max_length=50)),
                ('rack', models.ForeignKey(db_column='rack_id', on_delete=django.db.models.deletion.CASCADE, related_name='coordinates', to='warehouses.rack')),
            ],
            options={
                'db_table': 'rack_coordinates',
            },
        ),
    ]
