# Generated by Django 4.2.30 on 2026-05-25 04:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('warehouses', '0001_initial'),
        ('zones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rack',
            name='zone',
            field=models.ForeignKey(db_column='zone_id', on_delete=django.db.models.deletion.CASCADE, related_name='racks', to='zones.zone'),
        ),
        migrations.AddField(
            model_name='navigationnode',
            name='warehouse',
            field=models.ForeignKey(db_column='warehouse_id', on_delete=django.db.models.deletion.CASCADE, related_name='navigation_nodes', to='warehouses.warehouse'),
        ),
        migrations.AddField(
            model_name='mlextraction',
            name='object',
            field=models.ForeignKey(db_column='object_id', on_delete=django.db.models.deletion.CASCADE, related_name='ml_extractions', to='warehouses.cadobject'),
        ),
        migrations.AddField(
            model_name='cadobject',
            name='layout',
            field=models.ForeignKey(db_column='layout_id', on_delete=django.db.models.deletion.CASCADE, related_name='cad_objects', to='warehouses.warehouselayout'),
        ),
    ]
