# Generated by Django 4.2.30 on 2026-05-25 05:47

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('warehouses', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NavigationEdge',
            fields=[
                ('id', models.UUIDField(db_column='edge_id', default=uuid.uuid4, primary_key=True, serialize=False)),
                ('edge_weight', models.DecimalField(decimal_places=4, default=1.0, max_digits=10)),
                ('congestion_score', models.DecimalField(decimal_places=4, default=0.0, max_digits=5)),
                ('is_blocked', models.BooleanField(default=False)),
                ('travel_time', models.DecimalField(decimal_places=4, default=0.0, max_digits=10)),
                ('dynamic_cost', models.DecimalField(decimal_places=4, default=1.0, max_digits=10)),
                ('from_node', models.ForeignKey(db_column='from_node_id', on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_edges', to='warehouses.navigationnode')),
                ('to_node', models.ForeignKey(db_column='to_node_id', on_delete=django.db.models.deletion.CASCADE, related_name='incoming_edges', to='warehouses.navigationnode')),
                ('warehouse', models.ForeignKey(db_column='warehouse_id', on_delete=django.db.models.deletion.CASCADE, related_name='navigation_edges', to='warehouses.warehouse')),
            ],
            options={
                'db_table': 'navigation_edges',
                'unique_together': {('from_node', 'to_node')},
            },
        ),
    ]
